USE [GD1C2020]
GO
 

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Cliente(
ID_CLIENTE INT PRIMARY KEY,
CLIENTE_APELLIDO NVARCHAR(255),
CLIENTE_NOMBRE NVARCHAR(255),
CLIENTE_DNI DECIMAL(18,0),
CLIENTE_FECHA_NAC DATETIME2(3),
CLIENTE_MAIL NVARCHAR(255),
CLIENTE_TELEFONO INT
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Venta_Facturada(
FACTURA_NRO DECIMAL(18,0) PRIMARY KEY,
FACTURA_FECHA DATETIME2(3),
MONTO_TOTAL DECIMAL(18,2),
SUCURSAL_DIR NVARCHAR(255),
SUCURSAL_MAIL NVARCHAR(255),
SUCURSAL_TELEFONO DECIMAL(18,0)
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Fecha_Anio_Mes(
COMPRA_NUMERO DECIMAL(18,0) PRIMARY KEY,
COMPRA_ANIO SMALLINT,
COMPRA_MES TINYINT
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Compra(
COMPRA_NUMERO DECIMAL(18,0) PRIMARY KEY,
COMPRA_FECHA DATETIME2(3),
COSTO_TOTAL DECIMAL(18,2)
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Ruta_Aerea(
RUTA_ID INT PRIMARY KEY,
RUTA_AEREA_CODIGO DECIMAL(18,0)
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Vuelo(
VUELO_CODIGO DECIMAL(19,0) PRIMARY KEY,
VUELO_FECHA_SALIDA DATETIME2(3),
VUELO_FECHA_LLEGADA DATETIME2(3),
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Avion(
AVION_IDENTIFICADOR NVARCHAR(50) PRIMARY KEY,
AVION_MODELO NVARCHAR(50)
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Tipo_Pasaje(
ID_TIPO_PASAJE INT PRIMARY KEY,
TIPO_PASAJE_DESC NVARCHAR(255),
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Aerolinea(
ID_AEROLINEA INT IDENTITY(30,1) PRIMARY KEY,
AEROLINEA_NOMBRE NVARCHAR(255)
)
GO

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Ciudades(
ID_CIUDAD INT IDENTITY(30,1) PRIMARY KEY,
CIUDAD_NOMBRE NVARCHAR(255)
)
GO


 --Se crea la tabla de hechos hecho_pasaje_facturado

CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.Hecho_Pasaje_Facturado(
ID_FACT_PASAJE INT PRIMARY KEY,
FACTURA_NRO DECIMAL(18,0),
PASAJE_CODIGO DECIMAL(18,2),
PASAJE_PRECIO DECIMAL(18,2),
RUTA_ID INT,
ID_CLIENTE INT,
AVION_ID NVARCHAR(50),
PASAJE_GANANCIA DECIMAL(18,2), /*CALCULABLE*/
COMPRA_NUMERO DECIMAL(18,0),
COSTO_TOTAL DECIMAL(18,2),
VUELO_CODIGO DECIMAL(19,0),
ID_TIPO_PASAJE INT,
ID_AEROLINEA INT,
ID_CIUDAD_ORIGEN INT,
ID_CIUDAD_DESTINO INT,
ID_COMPRA_FECHA DECIMAL(18,0)
)
GO
 --Se crea la Dimension D_Proveedor_Hotel
 
CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Hotel(
HOTEL_ID INT PRIMARY KEY,
HOTEL_NOMBRE NVARCHAR(255),
HOTEL_CALLE NVARCHAR(50),
HOTEL_NRO_CALLE DECIMAL(18,0),
HOTEL_CANTIDAD_ESTRELLAS INT 
)
GO

 --Se crea la Dimension D_Habitacion
CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Habitacion(
ID_HABITACION INT PRIMARY KEY,
HOTEL_ID INT,
HABITACION_NUMERO DECIMAL(18,0),
HABITACION_PISO DECIMAL(18,0),
HABITACION_FRENTE NVARCHAR(50),
TIPO_HABITACION_CODIGO DECIMAL(18,0),
HABITACION_COSTO DECIMAL(18, 2),
HABITACION_PRECIO DECIMAL(18,2)
)
GO

 --Se crea la Dimension D_Habitacion_Vendida
CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Habitacion_Vendida(
ID_FACT_ESTADIA INT,
HABITACION_PRECIO DECIMAL(18,2)
)
GO

 --Se crea la Dimension D_Tipo_Habitacion
CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.D_Tipo_Habitacion(
TIPO_HABITACION_CODIGO DECIMAL(18,0) PRIMARY KEY,
TIPO_HABITACION_DESC NVARCHAR(50),
CANTIDAD_CAMAS TINYINT
)
GO

 --Se crea la tabla de Hecho_Estadia_Facturada
CREATE TABLE GESTIONADOS_POR_LA_PANDEMIA.Hecho_Estadia_Facturada(
ID_FACT_ESTADIA INT PRIMARY KEY,
FACTURA_NRO DECIMAL(18,0),
ESTADIA_CODIGO DECIMAL(18,0),
ESTADIA_CANTIDAD_NOCHES DECIMAL(18,0),
FECHA_CHECK_IN DATETIME2(3),
FECHA_CHECK_OUT DATETIME2(3),
PRECIO_ESTADIA DECIMAL(18,2),
ID_CLIENTE INT,
HOTEL_ID INT,
COMPRA_NUMERO DECIMAL(18,0),
COMPRA_FECHA DATETIME2(3),
ID_HABITACION INT,
TIPO_HABITACION_CODIGO DECIMAL(18,0)
)
GO

-----------

 --Se crea procedure para insertar datos en Dimension CLIENTE
CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionCliente
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Cliente(ID_CLIENTE, CLIENTE_APELLIDO, 
		CLIENTE_NOMBRE, CLIENTE_DNI, CLIENTE_FECHA_NAC, CLIENTE_MAIL, CLIENTE_TELEFONO)
	  SELECT DISTINCT ID_CLIENTE, CLIENTE_APELLIDO, CLIENTE_NOMBRE, CLIENTE_DNI, 
		CLIENTE_FECHA_NAC, CLIENTE_MAIL, CLIENTE_TELEFONO
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Cliente
	  WHERE ID_CLIENTE IS NOT NULL
	  AND CLIENTE_APELLIDO IS NOT NULL
	  AND CLIENTE_NOMBRE IS NOT NULL
	  AND CLIENTE_DNI IS NOT NULL
	  AND CLIENTE_FECHA_NAC IS NOT NULL
	  AND CLIENTE_MAIL IS NOT NULL
	  AND CLIENTE_TELEFONO IS NOT NULL
 END;
 GO

  --Se crea procedure para insertar datos en Dimension VENTA FACTURADA
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionVentaFacturada
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Venta_Facturada(FACTURA_NRO, FACTURA_FECHA,
		MONTO_TOTAL, SUCURSAL_DIR, SUCURSAL_MAIL, SUCURSAL_TELEFONO)
	  SELECT DISTINCT f.FACTURA_NRO, f.FACTURA_FECHA, f.MONTO_TOTAL,
		s.SUCURSAL_DIR, s.SUCURSAL_MAIL, s.SUCURSAL_TELEFONO
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Factura f, GESTIONADOS_POR_LA_PANDEMIA.Sucursal s 
	  WHERE	f.ID_SUCURSAL = s.ID_SUCURSAL 
	  AND f.FACTURA_NRO IS NOT NULL
	  AND f.FACTURA_FECHA IS NOT NULL
	  AND f.MONTO_TOTAL IS NOT NULL
	  AND s.SUCURSAL_DIR IS NOT NULL
	  AND s.SUCURSAL_MAIL IS NOT NULL
	  AND s.SUCURSAL_TELEFONO IS NOT NULL
 END;
 GO

 --Se crea procedure para insertar datos en Dimension COMPRA
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionCompra
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Compra(COMPRA_NUMERO,COMPRA_FECHA,COSTO_TOTAL)
	  SELECT DISTINCT COMPRA_NUMERO,COMPRA_FECHA, COSTO_TOTAL
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Compra
	  WHERE COMPRA_NUMERO IS NOT NULL
	  AND COSTO_TOTAL IS NOT NULL
 END;
 GO

  --Se crea procedure para insertar datos en Dimension FECHA ANIO MES
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionFechaAnioMes
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Fecha_Anio_Mes(COMPRA_NUMERO, COMPRA_ANIO, COMPRA_MES)
	  SELECT COMPRA_NUMERO, YEAR(COMPRA_FECHA), MONTH(COMPRA_FECHA)
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Compra 
	  WHERE COMPRA_FECHA IS NOT NULL
	  AND COMPRA_NUMERO IS NOT NULL
 END;
 GO


 --Se crea procedure para insertar datos en Dimension RUTA AEREA
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionRutaAerea
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Ruta_Aerea(RUTA_ID, RUTA_AEREA_CODIGO)
	  SELECT DISTINCT RUTA_ID, RUTA_AEREA_CODIGO
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Ruta_Aerea
	  WHERE RUTA_ID IS NOT NULL
	  AND RUTA_AEREA_CODIGO IS NOT NULL
 END;
 GO


  --Se crea procedure para insertar datos en Dimension VUELO
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionVuelo
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Vuelo(VUELO_CODIGO, VUELO_FECHA_SALIDA, VUELO_FECHA_LLEGADA)
	  SELECT DISTINCT VUELO_CODIGO, VUELO_FECHA_SALIDA, VUELO_FECHA_LLEGADA
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Vuelo
	  WHERE VUELO_CODIGO IS NOT NULL
	  AND VUELO_FECHA_SALIDA IS NOT NULL
	  AND VUELO_FECHA_LLEGADA IS NOT NULL
 END;
 GO


  --Se crea procedure para insertar datos en Dimension AVION
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionAvion
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Avion(AVION_IDENTIFICADOR, AVION_MODELO)
	  SELECT DISTINCT AVION_IDENTIFICADOR, AVION_MODELO
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Avion
	  WHERE AVION_IDENTIFICADOR IS NOT NULL
	  AND AVION_MODELO IS NOT NULL
 END;
 GO


  --Se crea procedure para insertar datos en Dimension TIPO PASAJE
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionTipoPasaje
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Tipo_Pasaje(ID_TIPO_PASAJE, TIPO_PASAJE_DESC)
	  SELECT DISTINCT BUTACA_ID, BUTACA_TIPO
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Butaca
	  WHERE BUTACA_ID IS NOT NULL
	  AND BUTACA_TIPO IS NOT NULL
 END;
 GO

   --Se crea procedure para insertar datos en Dimension PROVEEDOR AEROLINEA
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionProveedorAerolinea
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Aerolinea(AEROLINEA_NOMBRE)
	  SELECT DISTINCT AEROLINEA_NOMBRE
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Vuelo
	  WHERE AEROLINEA_NOMBRE IS NOT NULL
 END;
 GO

    --Se crea procedure para insertar datos en Dimension CIUDADES
CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionCiudades
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Ciudades(CIUDAD_NOMBRE)
	   SELECT DISTINCT CD.RUTA_AEREA_CIU_DESTINO as 'CIUDAD_NOMBRE'
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Ruta_Aerea CD
	  UNION SELECT DISTINCT CO.RUTA_AEREA_CIU_ORIGEN as 'CIUDAD_NOMBRE'
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Ruta_Aerea CO
	  WHERE RUTA_AEREA_CIU_DESTINO IS NOT NULL  
	  ORDER BY 'CIUDAD_NOMBRE' asc 
 END;
 GO

    --Se crea procedure para insertar datos en tabla de hechos pasaje facturado
CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarTablaHechosPasajeFacturado
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.Hecho_Pasaje_Facturado(ID_FACT_PASAJE, FACTURA_NRO, PASAJE_CODIGO, PASAJE_PRECIO, RUTA_ID, ID_CLIENTE, AVION_ID,
		COMPRA_NUMERO, COSTO_TOTAL, VUELO_CODIGO, ID_TIPO_PASAJE, ID_AEROLINEA, ID_CIUDAD_ORIGEN, ID_CIUDAD_DESTINO, ID_COMPRA_FECHA,PASAJE_GANANCIA)
	  SELECT DISTINCT pf.ID_FACT_PASAJE, f.FACTURA_NRO, p.PASAJE_CODIGO, p.PASAJE_PRECIO, r.RUTA_ID, cl.ID_CLIENTE, a.AVION_IDENTIFICADOR, c.COMPRA_NUMERO,
		c.COSTO_TOTAL, v.VUELO_CODIGO, b.BUTACA_ID, pa.ID_AEROLINEA, d1.ID_CIUDAD, d2.ID_CIUDAD, c.COMPRA_NUMERO, 
		"PASAJE_GANANCIA" = p.PASAJE_PRECIO - c.COSTO_TOTAL
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Pasaje_Facturado pf, 
		GESTIONADOS_POR_LA_PANDEMIA.Pasaje p,
		GESTIONADOS_POR_LA_PANDEMIA.Vuelo v,
		GESTIONADOS_POR_LA_PANDEMIA.Ruta_Aerea r,
		GESTIONADOS_POR_LA_PANDEMIA.Avion a,
		GESTIONADOS_POR_LA_PANDEMIA.Compra c,
		GESTIONADOS_POR_LA_PANDEMIA.Butaca b,
		GESTIONADOS_POR_LA_PANDEMIA.Factura f,
		GESTIONADOS_POR_LA_PANDEMIA.Cliente cl,
		GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Aerolinea pa,
		GESTIONADOS_POR_LA_PANDEMIA.D_Ciudades d1,
		GESTIONADOS_POR_LA_PANDEMIA.D_Ciudades d2
	  WHERE pf.PASAJE_CODIGO = p.PASAJE_CODIGO AND
		p.VUELO_CODIGO = v.VUELO_CODIGO AND
		v.RUTA_ID = r.RUTA_ID AND
		v.AVION_IDENTIFICADOR = a.AVION_IDENTIFICADOR AND
		p.COMPRA_NUMERO = c.COMPRA_NUMERO AND
		p.BUTACA_ID = b.BUTACA_ID AND
		pf.FACTURA_NRO = f.FACTURA_NRO AND
		f.ID_CLIENTE = cl.ID_CLIENTE AND
		v.AEROLINEA_NOMBRE = pa.AEROLINEA_NOMBRE AND
		r.RUTA_AEREA_CIU_ORIGEN = d1.CIUDAD_NOMBRE AND
		r.RUTA_AEREA_CIU_DESTINO = d2.CIUDAD_NOMBRE
		
		ORDER BY ID_FACT_PASAJE
 END;
 GO

-----


 --Se crea procedure para insertar datos en Dimension Proveedor Hotel

 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnDimensionHotel
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Hotel(HOTEL_ID,HOTEL_NOMBRE,HOTEL_CALLE,HOTEL_NRO_CALLE,HOTEL_CANTIDAD_ESTRELLAS)
	  SELECT DISTINCT HOTEL_ID, HOTEL_NOMBRE,HOTEL_CALLE,HOTEL_NRO_CALLE,HOTEL_CANTIDAD_ESTRELLAS 
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Hotel
	  WHERE HOTEL_NOMBRE IS NOT NULL
	  AND HOTEL_CALLE IS NOT NULL
	  OR HOTEL_NRO_CALLE IS NOT NULL
	  OR HOTEL_CANTIDAD_ESTRELLAS IS NOT NULL;
 END;
 GO
 

 --Se crea procedure para insertar datos en Dimension Tipo_Habitacion
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnDimensionTipoHabitacion
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Tipo_Habitacion(TIPO_HABITACION_CODIGO,TIPO_HABITACION_DESC, CANTIDAD_CAMAS)
	  SELECT distinct TIPO_HABITACION_CODIGO
      ,TIPO_HABITACION_DESC
	  ,"CANTIDAD_CAMAS" = 
	   CASE 
     WHEN TIPO_HABITACION_DESC = 'Base Simple' THEN 1 
	 WHEN TIPO_HABITACION_DESC = 'Base Doble' THEN 2 
	 WHEN TIPO_HABITACION_DESC = 'Base Triple' THEN 3 
	 WHEN TIPO_HABITACION_DESC = 'Base Cuadruple' THEN 4 
     ELSE 1
	 END
	FROM GESTIONADOS_POR_LA_PANDEMIA.Tipo_Habitacion
	  WHERE TIPO_HABITACION_CODIGO IS NOT NULL
 END;
 GO
 
 --Se crea procedure para insertar datos en Dimension Habitacion.
 CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnDimensionHabitacion
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.D_Habitacion(ID_HABITACION,HABITACION_NUMERO,HABITACION_PISO,HABITACION_FRENTE,TIPO_HABITACION_CODIGO, HABITACION_COSTO, HABITACION_PRECIO)
	  SELECT DISTINCT ID_HABITACION,HABITACION_NUMERO,HABITACION_PISO,HABITACION_FRENTE,TIPO_HABITACION_CODIGO, HABITACION_COSTO, HABITACION_PRECIO
	  FROM GESTIONADOS_POR_LA_PANDEMIA.Habitacion
	  WHERE HOTEL_ID IS NOT NULL
 END;
 GO

 --Se crea procedure para insertar datos en tabla HechoEstadiaFacturada.
CREATE PROCEDURE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnHechoEstadiaFacturada
 AS
 BEGIN
      INSERT INTO GESTIONADOS_POR_LA_PANDEMIA.Hecho_Estadia_Facturada(ID_FACT_ESTADIA,FACTURA_NRO,ESTADIA_CODIGO,ESTADIA_CANTIDAD_NOCHES,
	  FECHA_CHECK_IN,FECHA_CHECK_OUT,PRECIO_ESTADIA,ID_CLIENTE, HOTEL_ID,COMPRA_NUMERO,COMPRA_FECHA,ID_HABITACION,TIPO_HABITACION_CODIGO)
	SELECT EF.ID_FACT_ESTADIA,EF.FACTURA_NRO,E.ESTADIA_CODIGO,EF.ESTADIA_CANTIDAD_NOCHES,
	  EF.FECHA_CHECK_IN,EF.FECHA_CHECK_OUT,EF.PRECIO_ESTADIA,
	  F.ID_CLIENTE, H.HOTEL_ID,
	  C.COMPRA_NUMERO,C.COMPRA_FECHA,HA.ID_HABITACION,HA.TIPO_HABITACION_CODIGO
	FROM 
	GESTIONADOS_POR_LA_PANDEMIA.Estadia_Facturada EF
 INNER JOIN GESTIONADOS_POR_LA_PANDEMIA.Estadia E ON EF.ESTADIA_CODIGO=E.ESTADIA_CODIGO 
  INNER JOIN GESTIONADOS_POR_LA_PANDEMIA.Habitacion_Vendida HV ON EF.ID_FACT_ESTADIA=HV.ID_FACT_ESTADIA
 INNER JOIN GESTIONADOS_POR_LA_PANDEMIA.Habitacion HA ON HV.ID_HABITACION= HA.ID_HABITACION
 INNER JOIN GESTIONADOS_POR_LA_PANDEMIA.Hotel H ON HA.HOTEL_ID =H.HOTEL_ID
INNER JOIN GESTIONADOS_POR_LA_PANDEMIA.Factura F ON EF.FACTURA_NRO= F.FACTURA_NRO
INNER JOIN GESTIONADOS_POR_LA_PANDEMIA.Compra C ON  C.COMPRA_NUMERO=E.COMPRA_NUMERO
WHERE EF.ID_FACT_ESTADIA=HV.ID_FACT_ESTADIA
ORDER BY EF.ID_FACT_ESTADIA ASC ;
 END;
 GO

 --Se agregan las FK

ALTER TABLE GESTIONADOS_POR_LA_PANDEMIA.Hecho_Estadia_Facturada
ADD FOREIGN KEY(FACTURA_NRO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Venta_Facturada(FACTURA_NRO),
 FOREIGN KEY(ID_CLIENTE) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Cliente(ID_CLIENTE),
 FOREIGN KEY(HOTEL_ID) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Hotel(HOTEL_ID),
 FOREIGN KEY(COMPRA_NUMERO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Compra(COMPRA_NUMERO),
 FOREIGN KEY(ID_HABITACION) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Habitacion(ID_HABITACION),
 FOREIGN KEY(TIPO_HABITACION_CODIGO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Tipo_Habitacion(TIPO_HABITACION_CODIGO);

 --Se agregan las FK a la tabla de hechos
 ALTER TABLE GESTIONADOS_POR_LA_PANDEMIA.Hecho_Pasaje_Facturado
 	ADD FOREIGN KEY(FACTURA_NRO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Venta_Facturada(FACTURA_NRO),
	FOREIGN KEY(RUTA_ID) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Ruta_Aerea(RUTA_ID),	
	FOREIGN KEY(ID_CLIENTE) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Cliente(ID_CLIENTE),
	FOREIGN KEY(AVION_ID) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Avion(AVION_IDENTIFICADOR),
	FOREIGN KEY(COMPRA_NUMERO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Compra(COMPRA_NUMERO),
	FOREIGN KEY(VUELO_CODIGO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Vuelo(VUELO_CODIGO),
	FOREIGN KEY(ID_TIPO_PASAJE) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Tipo_Pasaje(ID_TIPO_PASAJE),
	FOREIGN KEY(ID_AEROLINEA) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Proveedor_Aerolinea(ID_AEROLINEA),
	FOREIGN KEY(ID_CIUDAD_ORIGEN) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Ciudades(ID_CIUDAD),
	FOREIGN KEY(ID_CIUDAD_DESTINO) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Ciudades(ID_CIUDAD),
	FOREIGN KEY(ID_COMPRA_FECHA) REFERENCES GESTIONADOS_POR_LA_PANDEMIA.D_Compra(COMPRA_NUMERO);
GO

-- Se ejecuta la carga de las tablas de Hechos y las dimensiones  --Ejecuto procedures

EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionCliente;
 GO

EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionVentaFacturada;
 GO

EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionCompra;
 GO

EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionFechaAnioMes;
 GO
 
EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionRutaAerea;
 GO
EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionVuelo;
 GO
EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionAvion;
 GO
EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionTipoPasaje;
 GO
EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionProveedorAerolinea;
 GO
EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDimensionCiudades;
 GO
 EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarTablaHechosPasajeFacturado;
 GO
 
 EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnDimensionHotel;
 GO

 EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnDimensionTipoHabitacion;
 GO

 EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnDimensionHabitacion;
 GO

EXECUTE GESTIONADOS_POR_LA_PANDEMIA.cargarDatosEnHechoEstadiaFacturada;
 GO
 